# Generated by Django 6.0.1 on 2026-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
